import { motion } from "framer-motion";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Scale, Building, Globe, AlertTriangle, FileText, Shield } from "lucide-react";
import { Footer } from "@/components/Footer";

const Legal = () => {
  const sections = [
    {
      title: "Company Information",
      icon: Building,
      content: [
        "Company Name: DYP Media & Publishing Limited",
        "Registered Office: [Address to be provided upon incorporation]",
        "Company Registration: [Number to be provided upon incorporation]",
        "Country of Incorporation: United Kingdom",
        "Business Type: Digital Entertainment and Gaming Platform"
      ]
    },
    {
      title: "Regulatory Status",
      icon: Scale,
      content: [
        "FYTEPIT is currently in development and does not hold any gambling or gaming licenses.",
        "We are actively working towards obtaining appropriate licenses for our intended operations.",
        "Current platform features are for entertainment and demonstration purposes only.",
        "No real-money gambling or betting is currently offered on the platform.",
        "We will update this notice once proper licensing is obtained."
      ]
    },
    {
      title: "Jurisdiction and Governing Law",
      icon: Globe,
      content: [
        "These terms and the use of FYTEPIT are governed by the laws of England and Wales.",
        "Any disputes arising from the use of this platform will be subject to the jurisdiction of English courts.",
        "Users from other jurisdictions use this platform at their own discretion.",
        "Local laws and regulations may apply to users in their respective jurisdictions.",
        "Users are responsible for ensuring their use complies with local laws."
      ]
    },
    {
      title: "Platform Development Status",
      icon: FileText,
      content: [
        "FYTEPIT is currently in active development and beta testing phase.",
        "Features and functionality may change as we continue to develop the platform.",
        "Some features shown are conceptual and may not be fully functional.",
        "We reserve the right to modify or discontinue features during development.",
        "User feedback and testing data help us improve the platform experience."
      ]
    },
    {
      title: "Disclaimers",
      icon: AlertTriangle,
      content: [
        "The platform is provided 'as is' without warranties of any kind, express or implied.",
        "We do not guarantee continuous, uninterrupted, or error-free operation of the platform.",
        "Fighter battle outcomes are generated by AI algorithms and are for entertainment purposes.",
        "Virtual fighter ownership does not constitute real-world asset ownership or investment securities.",
        "Platform performance and availability may vary during development and testing phases."
      ]
    },
    {
      title: "Future Commercial Operations",
      icon: Shield,
      content: [
        "Upon obtaining proper licenses, FYTEPIT intends to offer real-money gaming features.",
        "All commercial operations will be conducted in compliance with applicable regulations.",
        "Users will be notified of any changes to the platform's commercial status.",
        "Additional terms and conditions may apply once commercial operations begin.",
        "Age verification and responsible gaming measures will be implemented for commercial features."
      ]
    },
    {
      title: "Intellectual Property Rights",
      icon: FileText,
      content: [
        "All content, software, and materials on FYTEPIT are owned by DYP Media & Publishing Limited.",
        "The FYTEPIT name, logo, and branding are trademarks of DYP Media & Publishing Limited.",
        "Users retain rights to original content they create through WorldForge features.",
        "Platform usage grants DYP Media & Publishing Limited rights to use user-generated content.",
        "Third-party content used on the platform is properly licensed or used under fair use provisions."
      ]
    },
    {
      title: "Data Protection Compliance",
      icon: Shield,
      content: [
        "We comply with applicable data protection laws including GDPR where relevant.",
        "User data is processed in accordance with our Privacy Policy.",
        "We maintain appropriate technical and organizational security measures.",
        "Users have rights regarding their personal data as outlined in our Privacy Policy.",
        "Data processing is based on legitimate interests and user consent where required."
      ]
    },
    {
      title: "Platform Modifications",
      icon: FileText,
      content: [
        "We reserve the right to modify, suspend, or discontinue any part of the platform.",
        "Changes to core functionality will be communicated to users in advance when possible.",
        "We may update these legal terms as the platform evolves and regulations change.",
        "Users will be notified of significant changes to legal terms and conditions.",
        "Continued use of the platform constitutes acceptance of updated terms."
      ]
    },
    {
      title: "Contact Information",
      icon: Building,
      content: [
        "For legal inquiries: legal@fytepit.com",
        "For licensing questions: licensing@fytepit.com",
        "For general support: support@fytepit.com",
        "For business inquiries: business@fytepit.com",
        "Postal Address: [To be provided upon company incorporation]"
      ]
    }
  ];

  return (
    <div className="min-h-screen bg-background">
      {/* Hero Section */}
      <motion.section 
        className="relative overflow-hidden py-20 px-4"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.8 }}
      >
        <div className="absolute inset-0 bg-gradient-to-br from-primary/20 via-background to-secondary/20" />
        <div className="relative max-w-4xl mx-auto text-center">
          <motion.div
            className="flex items-center justify-center mb-6"
            initial={{ scale: 0, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            transition={{ delay: 0.2, duration: 0.6 }}
          >
            <div className="w-16 h-16 bg-primary/20 rounded-full flex items-center justify-center">
              <Scale className="w-8 h-8 text-primary" />
            </div>
          </motion.div>
          <motion.h1 
            className="text-5xl md:text-7xl font-bold mb-6 bg-gradient-to-r from-primary to-secondary bg-clip-text text-transparent"
            initial={{ y: 20, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            transition={{ delay: 0.4, duration: 0.8 }}
          >
            Legal Notice
          </motion.h1>
          <motion.p 
            className="text-xl md:text-2xl text-muted-foreground"
            initial={{ y: 20, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            transition={{ delay: 0.6, duration: 0.8 }}
          >
            Legal Information and Regulatory Status
          </motion.p>
        </div>
      </motion.section>

      {/* Legal Content */}
      <section className="py-20 px-4">
        <div className="max-w-4xl mx-auto">
          <motion.div
            className="bg-red-50 dark:bg-red-950/30 border border-red-200 dark:border-red-800 rounded-lg p-6 mb-12"
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            viewport={{ once: true }}
          >
            <div className="flex items-start gap-3">
              <AlertTriangle className="w-6 h-6 text-red-600 dark:text-red-400 mt-1 flex-shrink-0" />
              <div>
                <h3 className="text-red-800 dark:text-red-200 font-semibold mb-2">
                  Important Legal Disclaimer
                </h3>
                <p className="text-red-700 dark:text-red-300 text-sm leading-relaxed">
                  FYTEPIT is currently in development and does not hold gambling or gaming licenses. 
                  All current features are for demonstration and entertainment purposes only. 
                  No real-money transactions are currently processed.
                </p>
              </div>
            </div>
          </motion.div>

          <div className="space-y-8">
            {sections.map((section, index) => {
              const Icon = section.icon;
              return (
                <motion.div
                  key={section.title}
                  initial={{ opacity: 0, y: 40 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  transition={{ delay: index * 0.1, duration: 0.8 }}
                  viewport={{ once: true }}
                >
                  <Card className="border-border/50">
                    <CardHeader>
                      <CardTitle className="flex items-center gap-3 text-xl">
                        <div className="w-10 h-10 rounded-full bg-primary/20 flex items-center justify-center">
                          <Icon className="w-5 h-5 text-primary" />
                        </div>
                        {section.title}
                      </CardTitle>
                    </CardHeader>
                    <CardContent>
                      <ul className="space-y-3">
                        {section.content.map((point, idx) => (
                          <li key={idx} className="flex items-start gap-3">
                            <div className="w-2 h-2 rounded-full bg-primary mt-2 flex-shrink-0" />
                            <span className="text-muted-foreground leading-relaxed">{point}</span>
                          </li>
                        ))}
                      </ul>
                    </CardContent>
                  </Card>
                </motion.div>
              );
            })}
          </div>

          {/* Additional Legal Information */}
          <motion.div
            className="mt-16 bg-muted/50 rounded-lg p-8"
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            viewport={{ once: true }}
          >
            <h3 className="text-2xl font-bold mb-4 text-center">Legal Updates and Changes</h3>
            <div className="text-center text-muted-foreground space-y-4">
              <p>
                This legal notice will be updated as FYTEPIT progresses through development 
                and obtains necessary licenses and regulatory approvals.
              </p>
              <p>
                Users will be notified of significant legal or regulatory changes that may 
                affect their use of the platform.
              </p>
              <div className="pt-4 border-t border-border">
                <p className="text-sm">
                  For the most current legal information, please check this page regularly 
                  or contact our legal team at legal@fytepit.com
                </p>
              </div>
            </div>
          </motion.div>
        </div>
      </section>

      <Footer />
    </div>
  );
};

export default Legal;