// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fuifvbppttshpodpuqgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1aWZ2YnBwdHRzaHBvZHB1cWdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMzcyOTUsImV4cCI6MjA2OTkxMzI5NX0.hCQ8zWWtOyuOlMlXirhM4J1H1FxxR2002hpMB5ESqhY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});